function priceplot(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 25-Feb-2016 13:21:14

% Create figure

% Create axes
axes1 = axes('Parent',fig);
hold(axes1,'on');

% Create datetime plot
plot(X1,Y1,'Parent',axes1,'LineWidth',1.8);

% Create ylabel
ylabel('Prices');

% Create title
title('Price series');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[734436.48 736426.54]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'OuterPosition',[0 0.5 1 0.5]);
% Create axes
axes2 = axes('Parent',fig);
hold(axes2,'on');

% Create datetime plot
plot(X2,Y2,'Parent',axes2);

% Create xlabel
xlabel('Dates');

% Create ylabel
ylabel('Returns');

% Create title
title('Return series');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[734436.48 736397.52]);
box(axes2,'on');
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'OuterPosition',[0 0 1 0.5]);
